### ISSUE TITLE
Release 0.4 never published to crates.io

### ISSUE THREAD

**Issue by calavera** [axiomhq/rust-cuckoofilter#34]
I know this is duplicated from #30, but GitHub doesn't do a good job advertising new conversations in closed issues.

@seiflotfy, @florianjacob, @LukasKalbertodt  it'd be really appreciate it if any one of you could run `cargo publish`, it looks like the three of you are authors of this crate and you all should be able to do it.

I'm looking to this library to replace an old bloom filter implementation and the import/export feature added in 0.4 would be super useful for my use case.

Thanks a lot for writing this piece of code :pray:

**Comment by LukasKalbertodt** [comment]
Note: only *owners* of the package can release on crates.io, not necessarily the *authors*. The only owner is currently @seiflotfy.

**Comment by seiflotfy** [comment]
I'll transfer ownership to you in a bit

**Comment by LukasKalbertodt** [comment]
@seiflotfy I haven't received an owner invite by now, just FYI.

I'm not sure if I'm the right one to maintain this crate, but of course you can add me for now so that I can do some management stuff (like releasing a new version). I can still find a new maintainer afterwards. I'm glad to help out since you are currently lacking the time or motivation to maintain this (absolutely nothing wrong with that!) :)

Another possibility would be the "Rust Bus": https://users.rust-lang.org/t/bus-factor-1-for-crates/17046
A small organization for exactly these situations: keeping a crate alive when the original owner cannot put work into it, mostly because life. 

So just add me or someone of the Rust Bus as owner and we'll take care of the crate :)

**Comment by theli-ua** [comment]
Just pinging if there is any progress on this. Since its been half a year since last update

**Comment by stefandeml** [comment]
@seiflotfy just pining here as well. I would very much appreciate to keep the project alive,  before it is  forked or work is duplicated.

**Comment by seiflotfy** [comment]
On it

**Comment by seiflotfy** [comment]
@LukasKalbertodt you should have access now

**Comment by LukasKalbertodt** [comment]
@seiflotfy Thanks a ton, I did receive the GitHub and crates.io invite. I saw you already published 0.4.0.

I also saw that the repo was moved to `axiomhq`, which appears to be where you work. So what are your future plan for maintaining this crate? Do you want to actively maintain now? Or should I take the main role of maintainership (though I would probably delegate to someone else, but I'll see). In that case, the association with axiomhq is a bit strange though. But yeah, just tell me what your plans are! :)

**Comment by seiflotfy** [comment]
I am the co-founder of axiomhq but I have a couple of rust developers here
who don't mind getting involved. They are reading into cuckoofilters. But
this is open-source so whoever is working on ti gets to maintain it.

**Comment by LukasKalbertodt** [comment]
Ok, good to know. So I will assume that you all will be the main maintainers and I will just step in as a last backup if required. Great to see you back!

**Comment by LukasKalbertodt** [comment]
And since 0.4.0 was released, this can be closed.

**Comment by seiflotfy** [comment]
@LukasKalbertodt you are also a maintainer and feel free
